name: prisma-db-migrate
on: workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: asia-southeast2
  # project-name but it can be anything you want
  REPO_NAME: cc-main-backend
  INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
  DATABASE_URL: ${{ secrets.DATABASE_PROXY_URL }}
  DATABASE_INSTANCE: ${{ secrets.DATABASE_INSTANCE }}

jobs:
  migrate-database:
    name: Setup, Authenticate, and Migrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Download SQL Auth Proxy
        run: 'curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.1/cloud-sql-proxy.linux.amd64'

      - name: Make the Cloud SQL Auth proxy executable
        run: 'chmod +x cloud-sql-proxy'

      - name: Start the Cloud SQL proxy
        run: './cloud-sql-proxy $DATABASE_INSTANCE & npx prisma migrate deploy'
